package com.mycompany.queiungsystem;

import java.util.List;
import javax.swing.JTextField;

/**
 *
 * @author Arabelle Donor
 */
public class kitchen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(kitchen.class.getName());

    /**
     * Creates new form kitchen
     */

    private JTextField[] kitchenOrders;
    
    public kitchen() {
        initComponents();
        
        setSize(720,400);
        setLocation(407, 413); 
        
        kitchenOrders = new JTextField[]{order1, order2, order3, order4, order5, order6};
        
        order1.setEditable(false);
        order2.setEditable(false);
        order3.setEditable(false);
        order4.setEditable(false);
        order5.setEditable(false);
        order6.setEditable(false);
        
        ready1.setContentAreaFilled(false);
        ready1.setBorderPainted(false);
        ready1.setOpaque(false);
        
        ready2.setContentAreaFilled(false);
        ready2.setBorderPainted(false);
        ready2.setOpaque(false);
        
        ready3.setContentAreaFilled(false);
        ready3.setBorderPainted(false);
        ready3.setOpaque(false);
        
        ready4.setContentAreaFilled(false);
        ready4.setBorderPainted(false);
        ready4.setOpaque(false);
        
        ready5.setContentAreaFilled(false);
        ready5.setBorderPainted(false);
        ready5.setOpaque(false);
        
        ready6.setContentAreaFilled(false);
        ready6.setBorderPainted(false);
        ready6.setOpaque(false);
        
    }    
    
    public void displayOrderNumber(String orderNumber) {
        for (JTextField orderField : kitchenOrders) {
            if (orderField.getText().isEmpty()) {
                orderField.setText(orderNumber);
                break;
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ready1 = new javax.swing.JButton();
        order1 = new javax.swing.JTextField();
        order2 = new javax.swing.JTextField();
        order3 = new javax.swing.JTextField();
        order4 = new javax.swing.JTextField();
        order5 = new javax.swing.JTextField();
        order6 = new javax.swing.JTextField();
        ready2 = new javax.swing.JButton();
        ready3 = new javax.swing.JButton();
        ready4 = new javax.swing.JButton();
        ready5 = new javax.swing.JButton();
        ready6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ready1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ready1ActionPerformed(evt);
            }
        });

        order4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order4ActionPerformed(evt);
            }
        });

        order5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order5ActionPerformed(evt);
            }
        });

        ready2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ready2ActionPerformed(evt);
            }
        });

        ready3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ready3ActionPerformed(evt);
            }
        });

        ready4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ready4ActionPerformed(evt);
            }
        });

        ready5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ready5ActionPerformed(evt);
            }
        });

        ready6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ready6ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Arabelle Donor\\Downloads\\kitchen (7).png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(order1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(order2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(order3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(ready1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(ready2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(ready3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(order4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(order5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(order6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(ready4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(ready5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(ready6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(order1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(order2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(order3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ready1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ready2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ready3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(order4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(order5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(order6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ready4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ready5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ready6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ready1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ready1ActionPerformed

        String orderNum = order1.getText();

        if (orderNum != null && !orderNum.isEmpty()) {
            // Clear kitchen order1 field
            order1.setText("");

            // Call status frame to move number to ready1
            if (KFrame.woah != null) {
                KFrame.woah.setOrderReady(0, orderNum);  // Pass the number directly
            }
        }
        
    }//GEN-LAST:event_ready1ActionPerformed

    private void order5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_order5ActionPerformed

    private void ready2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ready2ActionPerformed

        String orderNum = order2.getText();

        if (orderNum != null && !orderNum.isEmpty()) {
            // Clear kitchen order1 field
            order2.setText("");

            // Call status frame to move number to ready1
            if (KFrame.woah != null) {
                KFrame.woah.setOrderReady(1, orderNum);  // Pass the number directly
            }
        }
        
    }//GEN-LAST:event_ready2ActionPerformed

    private void ready3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ready3ActionPerformed

        String orderNum = order3.getText();

        if (orderNum != null && !orderNum.isEmpty()) {
            // Clear kitchen order1 field
            order3.setText("");

            // Call status frame to move number to ready1
            if (KFrame.woah != null) {
                KFrame.woah.setOrderReady(2, orderNum);  // Pass the number directly
            }
        }
        
    }//GEN-LAST:event_ready3ActionPerformed

    private void ready4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ready4ActionPerformed

        String orderNum = order4.getText();

        if (orderNum != null && !orderNum.isEmpty()) {
            // Clear kitchen order1 field
            order4.setText("");

            // Call status frame to move number to ready1
            if (KFrame.woah != null) {
                KFrame.woah.setOrderReady(3, orderNum);  // Pass the number directly
            }
        }
        
    }//GEN-LAST:event_ready4ActionPerformed

    private void ready5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ready5ActionPerformed

        String orderNum = order5.getText();

        if (orderNum != null && !orderNum.isEmpty()) {
            // Clear kitchen order1 field
            order5.setText("");

            // Call status frame to move number to ready1
            if (KFrame.woah != null) {
                KFrame.woah.setOrderReady(4, orderNum);  // Pass the number directly
            }
        }
        
    }//GEN-LAST:event_ready5ActionPerformed

    private void ready6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ready6ActionPerformed

        String orderNum = order6.getText();

        if (orderNum != null && !orderNum.isEmpty()) {
            // Clear kitchen order1 field
            order6.setText("");

            // Call status frame to move number to ready1
            if (KFrame.woah != null) {
                KFrame.woah.setOrderReady(5, orderNum);  // Pass the number directly
            }
        }
        
    }//GEN-LAST:event_ready6ActionPerformed

    private void order4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_order4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new kitchen().setVisible(true));
        java.awt.EventQueue.invokeLater(() -> new status().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField order1;
    private javax.swing.JTextField order2;
    private javax.swing.JTextField order3;
    private javax.swing.JTextField order4;
    private javax.swing.JTextField order5;
    private javax.swing.JTextField order6;
    private javax.swing.JButton ready1;
    private javax.swing.JButton ready2;
    private javax.swing.JButton ready3;
    private javax.swing.JButton ready4;
    private javax.swing.JButton ready5;
    private javax.swing.JButton ready6;
    // End of variables declaration//GEN-END:variables
}
