package com.mycompany.queiungsystem;

import java.util.List;
import javax.swing.JTextField;

/**
 *
 * @author Arabelle Donor
 */
public class kitchen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(kitchen.class.getName());

    /**
     * Creates new form kitchen
     */

    private JTextField[] kitchenOrders;
    
    public kitchen() {
        initComponents();
        
        setSize(710,363);
        setLocation(407, 413); 
        
        kitchenOrders = new JTextField[]{order1, order2, order3, order4, order5, order6};
        
        order1.setEditable(false);
        order2.setEditable(false);
        order3.setEditable(false);
        order4.setEditable(false);
        order5.setEditable(false);
        order6.setEditable(false);
        
        ready1.setContentAreaFilled(false);
        ready1.setBorderPainted(false);
        ready1.setOpaque(false);
        
        ready2.setContentAreaFilled(false);
        ready2.setBorderPainted(false);
        ready2.setOpaque(false);
        
        ready3.setContentAreaFilled(false);
        ready3.setBorderPainted(false);
        ready3.setOpaque(false);
        
        ready4.setContentAreaFilled(false);
        ready4.setBorderPainted(false);
        ready4.setOpaque(false);
        
        ready5.setContentAreaFilled(false);
        ready5.setBorderPainted(false);
        ready5.setOpaque(false);
        
        ready6.setContentAreaFilled(false);
        ready6.setBorderPainted(false);
        ready6.setOpaque(false);
        
    }    
    
    public void displayOrderNumber(String orderNumber) {
        for (JTextField orderField : kitchenOrders) {
            if (orderField.getText().isEmpty()) {
                orderField.setText(orderNumber);
                break;
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ready1 = new javax.swing.JButton();
        order1 = new javax.swing.JTextField();
        order2 = new javax.swing.JTextField();
        order3 = new javax.swing.JTextField();
        order4 = new javax.swing.JTextField();
        order5 = new javax.swing.JTextField();
        order6 = new javax.swing.JTextField();
        ready2 = new javax.swing.JButton();
        ready3 = new javax.swing.JButton();
        ready4 = new javax.swing.JButton();
        ready5 = new javax.swing.JButton();
        ready6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(710, 363));
        setMinimumSize(new java.awt.Dimension(710, 363));
        setPreferredSize(new java.awt.Dimension(710, 363));
        getContentPane().setLayout(null);

        ready1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ready1ActionPerformed(evt);
            }
        });
        getContentPane().add(ready1);
        ready1.setBounds(50, 153, 160, 30);
        getContentPane().add(order1);
        order1.setBounds(40, 70, 180, 80);
        getContentPane().add(order2);
        order2.setBounds(270, 70, 170, 80);
        getContentPane().add(order3);
        order3.setBounds(490, 70, 180, 80);

        order4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order4ActionPerformed(evt);
            }
        });
        getContentPane().add(order4);
        order4.setBounds(40, 220, 180, 80);

        order5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order5ActionPerformed(evt);
            }
        });
        getContentPane().add(order5);
        order5.setBounds(270, 220, 170, 80);
        getContentPane().add(order6);
        order6.setBounds(490, 220, 180, 80);

        ready2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ready2ActionPerformed(evt);
            }
        });
        getContentPane().add(ready2);
        ready2.setBounds(270, 153, 170, 30);

        ready3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ready3ActionPerformed(evt);
            }
        });
        getContentPane().add(ready3);
        ready3.setBounds(500, 153, 160, 30);

        ready4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ready4ActionPerformed(evt);
            }
        });
        getContentPane().add(ready4);
        ready4.setBounds(50, 310, 160, 30);

        ready5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ready5ActionPerformed(evt);
            }
        });
        getContentPane().add(ready5);
        ready5.setBounds(270, 310, 170, 30);

        ready6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ready6ActionPerformed(evt);
            }
        });
        getContentPane().add(ready6);
        ready6.setBounds(500, 310, 160, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 250, 120);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kitchen.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(710, 363));
        jLabel3.setMinimumSize(new java.awt.Dimension(710, 363));
        jLabel3.setPreferredSize(new java.awt.Dimension(710, 363));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 710, 363);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ready1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ready1ActionPerformed

        String orderNum = order1.getText();

        if (orderNum != null && !orderNum.isEmpty()) {
            // Clear kitchen order1 field
            order1.setText("");

            // Call status frame to move number to ready1
            if (KFrame.woah != null) {
                KFrame.woah.setOrderReady(0, orderNum);  // Pass the number directly
            }
        }
        
    }//GEN-LAST:event_ready1ActionPerformed

    private void order5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_order5ActionPerformed

    private void ready2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ready2ActionPerformed

        String orderNum = order2.getText();

        if (orderNum != null && !orderNum.isEmpty()) {
            // Clear kitchen order1 field
            order2.setText("");

            // Call status frame to move number to ready1
            if (KFrame.woah != null) {
                KFrame.woah.setOrderReady(1, orderNum);  // Pass the number directly
            }
        }
        
    }//GEN-LAST:event_ready2ActionPerformed

    private void ready3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ready3ActionPerformed

        String orderNum = order3.getText();

        if (orderNum != null && !orderNum.isEmpty()) {
            // Clear kitchen order1 field
            order3.setText("");

            // Call status frame to move number to ready1
            if (KFrame.woah != null) {
                KFrame.woah.setOrderReady(2, orderNum);  // Pass the number directly
            }
        }
        
    }//GEN-LAST:event_ready3ActionPerformed

    private void ready4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ready4ActionPerformed

        String orderNum = order4.getText();

        if (orderNum != null && !orderNum.isEmpty()) {
            // Clear kitchen order1 field
            order4.setText("");

            // Call status frame to move number to ready1
            if (KFrame.woah != null) {
                KFrame.woah.setOrderReady(3, orderNum);  // Pass the number directly
            }
        }
        
    }//GEN-LAST:event_ready4ActionPerformed

    private void ready5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ready5ActionPerformed

        String orderNum = order5.getText();

        if (orderNum != null && !orderNum.isEmpty()) {
            // Clear kitchen order1 field
            order5.setText("");

            // Call status frame to move number to ready1
            if (KFrame.woah != null) {
                KFrame.woah.setOrderReady(4, orderNum);  // Pass the number directly
            }
        }
        
    }//GEN-LAST:event_ready5ActionPerformed

    private void ready6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ready6ActionPerformed

        String orderNum = order6.getText();

        if (orderNum != null && !orderNum.isEmpty()) {
            // Clear kitchen order1 field
            order6.setText("");

            // Call status frame to move number to ready1
            if (KFrame.woah != null) {
                KFrame.woah.setOrderReady(5, orderNum);  // Pass the number directly
            }
        }
        
    }//GEN-LAST:event_ready6ActionPerformed

    private void order4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_order4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new kitchen().setVisible(true));
        java.awt.EventQueue.invokeLater(() -> new status().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField order1;
    private javax.swing.JTextField order2;
    private javax.swing.JTextField order3;
    private javax.swing.JTextField order4;
    private javax.swing.JTextField order5;
    private javax.swing.JTextField order6;
    private javax.swing.JButton ready1;
    private javax.swing.JButton ready2;
    private javax.swing.JButton ready3;
    private javax.swing.JButton ready4;
    private javax.swing.JButton ready5;
    private javax.swing.JButton ready6;
    // End of variables declaration//GEN-END:variables
}
