/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.queiungsystem;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
/**
 *
 * @author Darex
 */
public class pos extends javax.swing.JFrame {

    DefaultTableModel model;
    public boolean hasPaid = false;

    /**
     * Creates new form pos
     */
    public pos() {
        initComponents();
        setSize(720,400);
        setTitle("Cashier");
        setLocation(407,12);
        
        total.setText("00.00");
        payment.setText("");
        sukli.setText("");
        
        model = new DefaultTableModel(new String[]{"Qty", "Item", "Price"}, 0);
        jTable1.setModel(model);
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
        
        payment.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != '.') {
                    e.consume();
                }
            }
        });   
    }
    
    private void calculateTotal() {
    double Total = 0;

    for (int i = 0; i < model.getRowCount(); i++) {
        double price = (double) model.getValueAt(i, 2); 
        Total += price;
    }

    total.setText(String.format("%.2f", Total)); 
}
    
    public void addToTable(String itemName, double unitPrice) {
   for (int i = 0; i < model.getRowCount(); i++) {
        String existingItem = (String) model.getValueAt(i, 1); 
        if (existingItem.equals(itemName)) {
            int currentQty = (int) model.getValueAt(i, 0);
            currentQty++;
            model.setValueAt(currentQty, i, 0);

            double newPrice = currentQty * unitPrice;
            model.setValueAt(newPrice, i, 2);

            calculateTotal();
            return;
        }
    }

    model.addRow(new Object[]{1, itemName, unitPrice});
    calculateTotal();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        pay = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        print = new javax.swing.JButton();
        typeorder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        total = new javax.swing.JLabel();
        payment = new javax.swing.JTextField();
        sukli = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        b1.setBorderPainted(false);
        b1.setContentAreaFilled(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(230, 60, 140, 80);

        b2.setBorderPainted(false);
        b2.setContentAreaFilled(false);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(390, 60, 140, 80);

        b3.setBorderPainted(false);
        b3.setContentAreaFilled(false);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(550, 60, 140, 80);

        b4.setBorderPainted(false);
        b4.setContentAreaFilled(false);
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(230, 170, 140, 80);

        b5.setBorderPainted(false);
        b5.setContentAreaFilled(false);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);
        b5.setBounds(390, 170, 140, 80);

        b6.setBorderPainted(false);
        b6.setContentAreaFilled(false);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);
        b6.setBounds(550, 170, 140, 80);

        pay.setBorderPainted(false);
        pay.setContentAreaFilled(false);
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        jPanel1.add(pay);
        pay.setBounds(550, 260, 140, 40);

        remove.setBorderPainted(false);
        remove.setContentAreaFilled(false);
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        jPanel1.add(remove);
        remove.setBounds(390, 260, 140, 40);

        cancel.setBorderPainted(false);
        cancel.setContentAreaFilled(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel);
        cancel.setBounds(390, 310, 140, 40);

        print.setBorderPainted(false);
        print.setContentAreaFilled(false);
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print);
        print.setBounds(550, 310, 150, 40);

        typeorder.setBorderPainted(false);
        typeorder.setContentAreaFilled(false);
        typeorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeorderActionPerformed(evt);
            }
        });
        jPanel1.add(typeorder);
        typeorder.setBounds(230, 310, 140, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "QTY", "ITEM", "PRICE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 200, 180);

        total.setText("jLabel2");
        jPanel1.add(total);
        total.setBounds(108, 273, 80, 16);

        payment.setText("payment");
        payment.setBorder(null);
        jPanel1.add(payment);
        payment.setBounds(108, 298, 80, 16);

        sukli.setText("sukli");
        jPanel1.add(sukli);
        sukli.setBounds(108, 320, 80, 16);

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SERVICE TYPE", "DINE IN", "TAKE OUT" }));
        jPanel1.add(combobox);
        combobox.setBounds(226, 260, 150, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cashier.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 710, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        addToTable("B1(THE BYTE MEAL)", 99.00);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        addToTable("B2(THE SNACK STACK)", 129.00);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
         addToTable("B3(FLAMIN' FIREWALL)", 249.00);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
         addToTable("B4(CHEAT CODE)", 289.00);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        addToTable("B5(KRAZY KERNEL)", 239.00);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        addToTable("B6(FULL STACK MEAL)", 299.00);
    }//GEN-LAST:event_b6ActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        
        String paymentInput = payment.getText().trim();
        if (paymentInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Input amount");
            hasPaid=false;
            return;
        }
        
    String transaction = combobox.getSelectedItem().toString().trim();
        if (transaction.equalsIgnoreCase("Service Type")) {
            JOptionPane.showMessageDialog(this, "Select a Type of Service");
            hasPaid=false;
            return;
        }

     try {
        double Total = Double.parseDouble(total.getText());
        double Payment = Double.parseDouble(payment.getText());
        
        if (Payment < Total) {
            JOptionPane.showMessageDialog(this, "Insufficient Payment!");
            hasPaid=false;
            return;
        }
        if (Payment >= Total) {
            double change = Payment - Total;
            sukli.setText(String.format("%.2f", change));
            hasPaid=true;
            JOptionPane.showMessageDialog(this, "Payment Successful!");
            
        }   
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Enter a valid payment amount.");
    }
     
     
    }//GEN-LAST:event_payActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
       int selectedRow = jTable1.getSelectedRow();

    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select an item to remove");
        return;
    }

    int currentQty = (int) model.getValueAt(selectedRow, 0); 
    double currentPrice = (double) model.getValueAt(selectedRow, 2); 
    double unitPrice = currentPrice / currentQty;

    while (true) {
        String input = JOptionPane.showInputDialog(this, 
                          "How many items you want to delete?");
        
        if (input == null) return; 

        try {
            int qtyToRemove = Integer.parseInt(input);

            if (qtyToRemove <= 0) {
                JOptionPane.showMessageDialog(this, "Enter a positive number.");
                continue;
            }

            if (qtyToRemove > currentQty) {
                JOptionPane.showMessageDialog(this, "Invalid Amount");
                continue; 
            }

           
            if (qtyToRemove == currentQty) {
                model.removeRow(selectedRow);
            } else {
                int newQty = currentQty - qtyToRemove;
                model.setValueAt(newQty, selectedRow, 0);
                model.setValueAt(newQty * unitPrice, selectedRow, 2);
            }

            calculateTotal(); 
            break; 

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid number.");
        }
    }
    }//GEN-LAST:event_removeActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       
        if (hasPaid) {
        JOptionPane.showMessageDialog(this, "You can't cancel paid items");
        return;
    }     
        
        if(jTable1.getRowCount  ()== 0){
            JOptionPane.showMessageDialog(this, "You don't have order to cancel");
        }else
        {
            int confirm=JOptionPane.showConfirmDialog(this,
                    "Do you want to cancel order?",
                    "Confirm Cancel", JOptionPane.YES_NO_OPTION);
                
            if(confirm==JOptionPane.YES_OPTION){
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                JOptionPane.showMessageDialog(this, "Order Cancelled Sucessfully!");
            }
        }
            
            
    }//GEN-LAST:event_cancelActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
       if (!hasPaid) {
        JOptionPane.showMessageDialog(this, "You need to make a Transaction");
        return;
    }       
    
    resibo res = new resibo();
    res.setVisible(true);
    this.setVisible(false);
    
    
    DefaultTableModel sourceModel = (DefaultTableModel) jTable1.getModel(); 
    DefaultTableModel targetModel = (DefaultTableModel) res.resiboTable.getModel(); 
    targetModel.setRowCount(0);
    
     for (int i = 0; i < sourceModel.getRowCount(); i++) {
        Object[] row = new Object[sourceModel.getColumnCount()];
        for (int j = 0; j < sourceModel.getColumnCount(); j++) {
            row[j] = sourceModel.getValueAt(i, j);
        }
        targetModel.addRow(row);
    }
     res.totalprice.setText(total.getText());  
    res.bayad.setText(payment.getText());    
    res.suklimo.setText(sukli.getText()); 
    String serviceType = combobox.getSelectedItem().toString();
    res.serv.setText(serviceType);
    }//GEN-LAST:event_printActionPerformed

    private void typeorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeorderActionPerformed
        
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Do you want to Add Order Number?",
            "Confirm",
            JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
        
            CashierAdd cash = new CashierAdd();
            cash.setVisible(true);
            setVisible(false);

        
        } else {
        
        }   
        
        
    }//GEN-LAST:event_typeorderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JLabel background;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JButton pay;
    public javax.swing.JTextField payment;
    private javax.swing.JButton print;
    private javax.swing.JButton remove;
    public javax.swing.JLabel sukli;
    public javax.swing.JLabel total;
    private javax.swing.JButton typeorder;
    // End of variables declaration//GEN-END:variables
}
