/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.queiungsystem;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
/**
 *
 * @author Darex
 */
public class pos11 extends javax.swing.JFrame {
DefaultTableModel model;
public boolean hasPaid = false;
    /**
     * Creates new form pos1
     */
    public pos11() {
        initComponents();
        this.setSize(800,500);
        this.setLocationRelativeTo(null);
        
        TOTAL.setText("00.00");
        payment1.setText("");
        sukli.setText("");
       
        
        model = new DefaultTableModel(new String[]{"Qty", "Item", "Price"}, 0);
        jTable1.setModel(model);
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
        
        
        payment1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != '.') {
                    e.consume();
                }
            }
        });    
        
        
    }
    
    public void addToTable(String itemName, double unitPrice) {
   for (int i = 0; i < model.getRowCount(); i++) {
        String existingItem = (String) model.getValueAt(i, 1); 
        if (existingItem.equals(itemName)) {
            int currentQty = (int) model.getValueAt(i, 0);
            currentQty++;
            model.setValueAt(currentQty, i, 0);

            double newPrice = currentQty * unitPrice;
            model.setValueAt(newPrice, i, 2);

            calculateTotal();
            return;
        }
    }

    model.addRow(new Object[]{1, itemName, unitPrice});
    calculateTotal();
}
  
 //-------------------------------------------------------------------------------------------//       
    
    
    private void calculateTotal() {
    double total = 0;

    for (int i = 0; i < model.getRowCount(); i++) {
        double price = (double) model.getValueAt(i, 2); 
        total += price;
    }

    TOTAL.setText(String.format("%.2f", total)); 
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        printresibo = new javax.swing.JButton();
        removeitem = new javax.swing.JButton();
        cencelorder = new javax.swing.JButton();
        pay = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        payment1 = new javax.swing.JTextField();
        TOTAL = new javax.swing.JLabel();
        sukli = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 0, 0, 0));
        setUndecorated(true);

        jPanel1.setLayout(null);

        printresibo.setBorderPainted(false);
        printresibo.setContentAreaFilled(false);
        printresibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printresiboActionPerformed(evt);
            }
        });
        jPanel1.add(printresibo);
        printresibo.setBounds(255, 397, 169, 48);

        removeitem.setBorderPainted(false);
        removeitem.setContentAreaFilled(false);
        removeitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeitemActionPerformed(evt);
            }
        });
        jPanel1.add(removeitem);
        removeitem.setBounds(435, 340, 167, 48);

        cencelorder.setBorderPainted(false);
        cencelorder.setContentAreaFilled(false);
        cencelorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cencelorderActionPerformed(evt);
            }
        });
        jPanel1.add(cencelorder);
        cencelorder.setBounds(436, 396, 167, 48);

        pay.setBorderPainted(false);
        pay.setContentAreaFilled(false);
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        jPanel1.add(pay);
        pay.setBounds(617, 340, 166, 103);

        b1.setBorderPainted(false);
        b1.setContentAreaFilled(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(260, 96, 160, 100);

        b2.setBorderPainted(false);
        b2.setContentAreaFilled(false);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(440, 96, 160, 90);

        b3.setBorderPainted(false);
        b3.setContentAreaFilled(false);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(620, 96, 160, 100);

        b4.setBorderPainted(false);
        b4.setContentAreaFilled(false);
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(260, 218, 160, 90);

        b5.setBorderPainted(false);
        b5.setContentAreaFilled(false);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);
        b5.setBounds(440, 218, 160, 90);

        b6.setBorderPainted(false);
        b6.setContentAreaFilled(false);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);
        b6.setBounds(620, 218, 160, 90);

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "QTY", "ITEM", "PRICE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 230, 240);

        payment1.setBorder(null);
        payment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment1ActionPerformed(evt);
            }
        });
        jPanel1.add(payment1);
        payment1.setBounds(118, 382, 100, 16);
        jPanel1.add(TOTAL);
        TOTAL.setBounds(118, 355, 100, 20);
        jPanel1.add(sukli);
        sukli.setBounds(118, 406, 100, 20);

        combobox.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SERVICE TYPE", "DINE IN", "TAKE OUT" }));
        jPanel1.add(combobox);
        combobox.setBounds(255, 338, 167, 49);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cashier.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printresiboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printresiboActionPerformed
    if (!hasPaid) {
        JOptionPane.showMessageDialog(this, "You need to make a Transaction");
        return;
    }       
    
    resibo res = new resibo();
    res.setVisible(true);
    this.setVisible(false);
    
    
    DefaultTableModel sourceModel = (DefaultTableModel) jTable1.getModel(); 
    DefaultTableModel targetModel = (DefaultTableModel) res.resiboTable.getModel(); 
    targetModel.setRowCount(0);
    
     for (int i = 0; i < sourceModel.getRowCount(); i++) {
        Object[] row = new Object[sourceModel.getColumnCount()];
        for (int j = 0; j < sourceModel.getColumnCount(); j++) {
            row[j] = sourceModel.getValueAt(i, j);
        }
        targetModel.addRow(row);
    }
     res.totalprice.setText(TOTAL.getText());  
    res.bayad.setText(payment1.getText());    
    res.suklimo.setText(sukli.getText()); 
    String serviceType = combobox.getSelectedItem().toString();
    res.serv.setText(serviceType);
    
    
    }//GEN-LAST:event_printresiboActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
    
    String paymentInput = payment1.getText().trim();
        if (paymentInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Input amount");
            hasPaid=false;
            return;
        }
        
    String transaction = combobox.getSelectedItem().toString().trim();
        if (transaction.equalsIgnoreCase("Service Type")) {
            JOptionPane.showMessageDialog(this, "Select a Type of Service");
            hasPaid=false;
            return;
        }

     try {
        double total = Double.parseDouble(TOTAL.getText());
        double payment = Double.parseDouble(payment1.getText());
        
        if (payment < total) {
            JOptionPane.showMessageDialog(this, "Insufficient Payment!");
            hasPaid=false;
            return;
        }
        if (payment >= total) {
            double change = payment - total;
            sukli.setText(String.format("%.2f", change));
            hasPaid=true;
            JOptionPane.showMessageDialog(this, "Payment Successful!");
            
        }   
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Enter a valid payment amount.");
    }
     
     
    }//GEN-LAST:event_payActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
         addToTable("B1(THE BYTE MEAL)", 99.00);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        addToTable("B2(THE SNACK STACK)", 129.00);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
         addToTable("B3(FLAMIN' FIREWALL)", 249.00);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
         addToTable("B4(CHEAT CODE)", 289.00);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        addToTable("B5(KRAZY KERNEL)", 239.00);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        addToTable("B6(FULL STACK MEAL)", 299.00);
    }//GEN-LAST:event_b6ActionPerformed

    private void payment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payment1ActionPerformed

    private void removeitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeitemActionPerformed
    int selectedRow = jTable1.getSelectedRow();

    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select an item to remove");
        return;
    }

    int currentQty = (int) model.getValueAt(selectedRow, 0); 
    double currentPrice = (double) model.getValueAt(selectedRow, 2); 
    double unitPrice = currentPrice / currentQty;

    while (true) {
        String input = JOptionPane.showInputDialog(this, 
                          "How many items you want to delete?");
        
        if (input == null) return; 

        try {
            int qtyToRemove = Integer.parseInt(input);

            if (qtyToRemove <= 0) {
                JOptionPane.showMessageDialog(this, "Enter a positive number.");
                continue;
            }

            if (qtyToRemove > currentQty) {
                JOptionPane.showMessageDialog(this, "Invalid Amount");
                continue; 
            }

           
            if (qtyToRemove == currentQty) {
                model.removeRow(selectedRow);
            } else {
                int newQty = currentQty - qtyToRemove;
                model.setValueAt(newQty, selectedRow, 0);
                model.setValueAt(newQty * unitPrice, selectedRow, 2);
            }

            calculateTotal(); 
            break; 

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid number.");
        }
    }

    }//GEN-LAST:event_removeitemActionPerformed

    private void cencelorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cencelorderActionPerformed
  
        
        int choice = JOptionPane.showConfirmDialog(
            this, 
            "Do you want to proceed?", 
            "Cancel Transaction", 
            JOptionPane.YES_NO_OPTION
            );

    if (choice == JOptionPane.YES_OPTION) {
        // Clear all rows in the table
        model.setRowCount(0);

        // Reset total, payment, change
        TOTAL.setText("00.00");
        payment1.setText("");
        sukli.setText("");
    }
    }//GEN-LAST:event_cencelorderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pos11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pos11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pos11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pos11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pos11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TOTAL;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton cencelorder;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pay;
    private javax.swing.JTextField payment1;
    private javax.swing.JButton printresibo;
    private javax.swing.JButton removeitem;
    private javax.swing.JLabel sukli;
    // End of variables declaration//GEN-END:variables
}
