/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.queiungsystem;


import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Darex
 */
public class resibo2 extends javax.swing.JFrame {

    DefaultTableModel receiptModel;
    
    public resibo2() {
        initComponents();
        setSize(720,400);
        setTitle("Receipt");
        setLocation(407,12);
        
        resiboTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        resiboTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        resiboTable.getColumnModel().getColumn(2).setPreferredWidth(30);
        
          receiptModel = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Qty", "Item", "Price"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        resiboTable.setModel(receiptModel); 
        
        //-----------------------------------------------------------------------------------//
        
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String currentDate = LocalDate.now().format(dateFormatter);
        date.setText(currentDate);
        
        
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("hh:mm:a");
        String currentTime = LocalTime.now().format(timeFormatter);
        time.setText(currentTime);
        
        
        Random rand = new Random();
        StringBuilder refNumBuilder = new StringBuilder();
            for (int i = 0; i < 12; i++) {
                refNumBuilder.append(rand.nextInt(10)); // Digits 0–9
            }
                ref.setText(refNumBuilder.toString());
    } 
    public void sendToReceipt() {
        resibo2 receiptFrame = new resibo2(); // create the receipt frame

        DefaultTableModel receiptModel = new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Qty", "Item", "Price"}
    )   {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

        testing tes = new testing();
        DefaultTableModel model = (DefaultTableModel) tes.jTable1.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                Object qty = model.getValueAt(i, 2);    // Quantity
                Object item = model.getValueAt(i, 1);   // Item
                Object price = model.getValueAt(i, 3);  // Price

        if (qty != null && item != null && price != null &&
            !qty.toString().isEmpty() && !item.toString().equals("ORDER ITEMS:")) {
            receiptModel.addRow(new Object[]{qty, item, price});
        }
    }

    
    receiptFrame.resiboTable.setModel(receiptModel);

   
    receiptFrame.totalprice.setText(tes.totalprice2.getText());
    receiptFrame.bayad.setText(tes.payment2.getText());
    receiptFrame.suklimo.setText(tes.sukli2.getText());

    
    receiptFrame.setVisible(true);
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resiboTable = new javax.swing.JTable();
        serv = new javax.swing.JLabel();
        ref = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        totalprice = new javax.swing.JLabel();
        bayad = new javax.swing.JLabel();
        suklimo = new javax.swing.JLabel();
        bakgrounf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        resiboTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(resiboTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(250, 170, 210, 110);

        serv.setText("jLabel2");
        jPanel1.add(serv);
        serv.setBounds(340, 150, 38, 16);

        ref.setText("jLabel3");
        jPanel1.add(ref);
        ref.setBounds(320, 114, 80, 16);

        date.setText("jLabel4");
        jPanel1.add(date);
        date.setBounds(300, 130, 38, 16);

        time.setText("jLabel5");
        jPanel1.add(time);
        time.setBounds(410, 130, 38, 16);

        totalprice.setText("jLabel6");
        jPanel1.add(totalprice);
        totalprice.setBounds(410, 283, 50, 16);

        bayad.setText("jLabel7");
        jPanel1.add(bayad);
        bayad.setBounds(410, 298, 50, 16);

        suklimo.setText("jLabel8");
        jPanel1.add(suklimo);
        suklimo.setBounds(410, 313, 50, 16);

        bakgrounf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/receipt.png"))); // NOI18N
        jPanel1.add(bakgrounf);
        bakgrounf.setBounds(0, -20, 710, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resibo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resibo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resibo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resibo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resibo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bakgrounf;
    private javax.swing.JLabel bayad;
    private javax.swing.JLabel date;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ref;
    private javax.swing.JTable resiboTable;
    private javax.swing.JLabel serv;
    private javax.swing.JLabel suklimo;
    private javax.swing.JLabel time;
    private javax.swing.JLabel totalprice;
    // End of variables declaration//GEN-END:variables
}
