/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.queiungsystem;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import java.awt.*;
/**
 *
 * @author Darex
 */
public class resibo extends javax.swing.JFrame {

    /**
     * Creates new form resibo
     */
    public resibo() {
        initComponents();
        this.setSize(800,500);
        
        resiboTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        resiboTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        resiboTable.getColumnModel().getColumn(2).setPreferredWidth(30);
        
        
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String currentDate = LocalDate.now().format(dateFormatter);
        date.setText(currentDate);
        
        
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        String currentTime = LocalTime.now().format(timeFormatter);
        time.setText(currentTime);
        
        
        Random rand = new Random();
        StringBuilder refNumBuilder = new StringBuilder();
            for (int i = 0; i < 12; i++) {
                refNumBuilder.append(rand.nextInt(10)); // Digits 0–9
            }
                ref.setText(refNumBuilder.toString());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resiboTable = new javax.swing.JTable();
        serv = new javax.swing.JLabel();
        totalprice = new javax.swing.JLabel();
        bayad = new javax.swing.JLabel();
        suklimo = new javax.swing.JLabel();
        ref = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(null);

        resiboTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "QTY", "ITEM", "PRICE"
            }
        ));
        jScrollPane1.setViewportView(resiboTable);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(270, 210, 250, 140);
        jPanel2.add(serv);
        serv.setBounds(366, 185, 70, 20);
        jPanel2.add(totalprice);
        totalprice.setBounds(480, 350, 60, 20);
        jPanel2.add(bayad);
        bayad.setBounds(470, 370, 70, 20);
        jPanel2.add(suklimo);
        suklimo.setBounds(470, 390, 70, 20);
        jPanel2.add(ref);
        ref.setBounds(350, 130, 80, 20);
        jPanel2.add(date);
        date.setBounds(320, 150, 80, 20);
        jPanel2.add(time);
        time.setBounds(460, 150, 60, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/queiungsystem/receipt.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resibo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel bayad;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ref;
    public javax.swing.JTable resiboTable;
    public javax.swing.JLabel serv;
    public javax.swing.JLabel suklimo;
    private javax.swing.JLabel time;
    public javax.swing.JLabel totalprice;
    // End of variables declaration//GEN-END:variables
}
